#+TITLE: Reviews

* Daily
** 2020
*** Aug
**** 20
***** GCSE Results
Today was the day that i got the majority of my GCSE results see the table below.
| Subject            | Grade |
|--------------------+-------|
| English Language   |     7 |
| English Literature |     7 |
| French             |     6 |
| Latin              |     6 |
| Geography          |     8 |
| Maths              |     9 |
| CS                 |     9 |
| Combined Science   |   9-9 |

I personally am very happy with these results especially english as i consistently got 6s throughout the years.
***** New Laptop
Due to these results my parents have agreed to add 500 pounds to the laptop stockpile and this has allowed me to upgrade it from the ryzen 3 4300u to the ryzen 5 4500u lenovo flex 5 which will be picked up tomorrow. The interesting thing is that many people have said that the laptop will come with a pen and others have said that it won't, therefore we will see what happens.
**** 21
***** Laptop
Today I picked up my laptop and immediately I felt that it was a really good laptop which has been reinforced throughout the rest of the day. I was a bit dissappointed to find that it didn't come with a pen however that was quite expected as the curry's page was quite amiguous therefore this was not much of a surprise. After this I started to install arch which I should probably left to tomorrow since I started about an hour ago. The install so far hasn't gone very smoothly however I feel that it shall be completed by tomorrow (I have had some confusion as to which partitioning scheme should be used).
***** Rest of day
The rest of the day was mostly spent in anticipation of this however it was the first time entering a shop after lockdown which I had some level of apprehension for which mostly wasn't required however I am happy that this experience is now behind me as the first time is always the most difficult.
**** 22
***** Installing Arch
After writing yesterday's review I found a video explaining how to install arch which was very consise at only 20 minutes. In the video he used an mbr partitioning scheme for legacy bios however this ended up not working with my install due to me not knowing how to use the ~grub-install~ command, therefore I ended up going with a gpt partitioning scheme without the swap partition that I created at first.
***** Installing other software
After installing Arch I installed all of the standard software i.e. xorg, qtile etc. and surprisingly the volume, backlight and wifi widgets built into qtile didn't seem to work which was unfortunate because it meant that I had to write them myself but that wasn't much of a big deal.
