#+TITLE: Reviews

* Daily
** 2020
*** Aug
**** 20
***** GCSE Results
Today was the day that i got the majority of my GCSE results see the table below.
| Subject            | Grade |
|--------------------+-------|
| English Language   |     7 |
| English Literature |     7 |
| French             |     6 |
| Latin              |     6 |
| Geography          |     8 |
| Maths              |     9 |
| CS                 |     9 |
| Combined Science   |   9-9 |

I personally am very happy with these results especially english as i consistently got 6s throughout the years.
***** New Laptop
Due to these results my parents have agreed to add 500 pounds to the laptop stockpile and this has allowed me to upgrade it from the ryzen 3 4300u to the ryzen 5 4500u lenovo flex 5 which will be picked up tomorrow. The interesting thing is that many people have said that the laptop will come with a pen and others have said that it won't, therefore we will see what happens.
**** 21
***** Laptop
Today I picked up my laptop and immediately I felt that it was a really good laptop which has been reinforced throughout the rest of the day. I was a bit dissappointed to find that it didn't come with a pen however that was quite expected as the curry's page was quite amiguous therefore this was not much of a surprise. After this I started to install arch which I should probably left to tomorrow since I started about an hour ago. The install so far hasn't gone very smoothly however I feel that it shall be completed by tomorrow (I have had some confusion as to which partitioning scheme should be used).
***** Rest of day
The rest of the day was mostly spent in anticipation of this however it was the first time entering a shop after lockdown which I had some level of apprehension for which mostly wasn't required however I am happy that this experience is now behind me as the first time is always the most difficult.
**** 22
***** Installing Arch
After writing yesterday's review I found a video explaining how to install arch which was very consise at only 20 minutes. In the video he used an mbr partitioning scheme for legacy bios however this ended up not working with my install due to me not knowing how to use the ~grub-install~ command, therefore I ended up going with a gpt partitioning scheme without the swap partition that I created at first.
***** Installing other software
After installing Arch I installed all of the standard software i.e. xorg, qtile etc. and surprisingly the volume, backlight and wifi widgets built into qtile didn't seem to work which was unfortunate because it meant that I had to write them myself but that wasn't much of a big deal.
**** 23
***** Socializing
Today I talked to James for a while which seemed to be much needed since I felt much better after I had done this.
***** Computing
I also wrote a very sucessful script to automatically sync my org documents with my laptop using git, it seems to work quite well so far.

* Weekly
** 2020
*** 34
**** org-mode
This week I have properly learned org-mode and started to actually organise my life which so far has been very useful. I have created a structure to these reviews and am attempting to do them every day. I have also been forming a todo system which has been beneficial for me as I am starting to remember which tasks I have to do.
**** GCSE Results
This week I recieved all of my GCSE Results which I am very pleased with and think that I probably got better marks given by teachers than I would have managed if there had been actual exams which I think is probably not a good thing however I am still very happy with my results. The table can be seen in the daily review for the daily review on Aug 20 2020.
**** Laptop
This week due to my good results my parents decided to add 500 pounds to the new laptop fund which I used to buy the better specced version of the laptop than I had originally intended which was very nice although I still need to wait until the 27th to order a pen for it which is somewhat unfortunate but it can't be helped. As soon as I recieved it I installed arch (not without hiccups) and then installed the rest of the software. The touch screen is a really nice feature for sitting in bed scrolling through youtube and it is a breath of fresh air to have a twm on my laptop.
**** Other Tech
This week I also recieved the graphing calculator that I will have to use for the IB. So far in my experience the calculator is very fully featured and I think that I will have a lot of joy in using it. The big thing that surprised me (even though I should have been expecting it) was that the 4-directional pad below the display was actually a capacitive touchpad which makes the calculator bearable to use even though I shouldn't use it for maximum efficiency.
**** Looking forward
I think that over the next few weeks I should try to flesh out my reviews system and I will start writing morning pages as I hope that will concentrate me more come the start of the IB so that I will be more organised which will be my downfall if anything over the next two years.
