#+TITLE: English Language & Literature
#+NAME: Oscar Morris
#+TEACHER: Mr Proudfoot
#+ROOM: E4

* Ghosts
* The Crucible
* Poetry (Carol Ann Duffy)
** Anne Hathaway
*** TODO Do some research about the poem
DEADLINE: <2020-08-28 Fri 12:15>

- written in a sonnet form
* The Great Gatsby
* Articles
* Adverts
* Speeches
* Propaganda Posters
* Course Structure
** General
- The course has a three part structure according to the three areas of exploration.
- No Assessment is tied to a particular part of the course so you can use any of the texts studied for any assessment (you cannot use the same work twice).
- The questions are very general which enables you to talk about whatever you want (relating to the question)
- Example questions from paper 2:
  + Referring to two of the works you have studied, discuss both how and why the text invites the reader to identify with situations, characters and/or ideas.
** Areas of Exploration
*** Readers, Writers and Texts
*** Time and Space
*** Intertextuality and connecting texts
** Fields of Inquiry
*** Culture, identity and community
*** Beliefs, power and justice
*** Art, creativity and the imagination
*** Science, technology and the environment
** Central Concepts
*** Identity
*** Culture
*** Creativity
*** Communication
*** Transformation
*** Perspective
*** Representation
** LangLit (SL)
Study of 4 literary works and at least 4 non-literary texts, covering:
 - 2 literary forms
 - 2 periods
 - 2 Places
 - 1 English work
 - 1 work in translation
 - 2 "Free choices"
** Works vs Texts
*** Literary Works
- Drama
- Poetry
- Prose: Fiction
- Prose Non-Fiction
*** Literary Texts
- Essays
- Biographies
- Letters
- etc.
** Breakdown of final Grade
| Exam            |   % |
|-----------------+-----|
| Exam Paper 1    | 35% |
| Exam Paper 2    | 35% |
| Oral Assessment | 30% |

*** Exam Paper 1
Unseen Guided Textual Analysis

The paper consists of two passages from two different non-literary text types, each accompanied by a question. Students choose one passage and write an analysis of it (20 marks)
*** Exam Paper 2
The paper consists od four general questions. In response to one question, students will
*** Oral Assessment (15 mins)
Supported by an extract from one literary work and one non-literary text, students will offer a prepared response of 15 minutes to the following prompt:
Examine the ways in thich the global issue of your choice
