#+TITLE: English Language & Literature
#+NAME: Oscar Morris
#+TEACHER: Mr Proudfoot
#+ROOM: E4

* Ghosts
* The Crucible
* Poetry (Carol Ann Duffy)
** The World's Wife :anthology:
*** Themes
- Duffy's collection mostly focuses on the unheard perspectives of female counterparts of famous male figures
  + It is "giving a voice to the wives of famous and infamous 'great men' of world literature and civilisation"
- It covers the issues surrounding marriage, sex, love, motherhood etc. being the "typical" roles of women
- She seems to be attempting to subvert the classical traditions of male poets and a female muse
- She often seems to mirror the literature of the husbands of those she is trying to portray for example "Anne Hathaway" is written as a sonnet mirroroing Shakespears's countless sonnets and "Mrs Darwin" is written almost as a diary entry mirroring Darwin's originals
*** Duffy as Poet Laureate
**** The position of Poet Laureate
The origins of the Poet Laureateship date back to teh 17th century (1616) when James I of England grantes a pension to the writer Ben Jonson.
Although there were subsequent court poets it was not until 1668 and the appointment of John Dryden by Charles II that the post was made sn established royal office within the royal household.
John Dryden was the only poet to have been removed from office due to him being a catholic convert he refused to take the oath of alliegance to the new protestant monarchs William III and Mary II.
** Anne Hathaway :poem:
*** Context
**** Anne Hathaway herself
- She was Shakespeare's wife
- She was seven years older than Shakespeare when they married and Anne was already pregnant
- She was widowed before marrying Shakespeare
**** The Poem
- written in a sonnet form
  + 14 lines
  + usually ends in a rhyming couplet
  + usually 3 quartets
- comes from Her first themed collection of poems (The World's Wife)
- begins with an epigraph taken from Shakespeare's will leaving Anne his "second best bed" which was in fact the couple's maritial bed as the best was reserved for guests. Some critics have said that this was an insult however Duffy portrays this as Shakespeare's last romantic guesture to his wife. The beds of prosperous citizens were expensive often reaching prices equivalent to a small house. And it was customary for the wife to recieve the second best furniture and for the children to recieve the best. It was also customary for the best bed to be used for guests and the second best for the couple themselves.
- She is giving a voice to someone that may not have had a voice
*** The Bed
- can be seen as a aymbol for their everlasting love. She is able to look after the bed after her spouse has died.
- It has this symbolic value due to the context of the times
- It is used as a metaphor for their love
*** Their Love
- The line "Romance and drama played by touch, by scent, by taste." uses all of the senses gives us a sensory description which could reflect the physicality of their love furthermore Duffy's use of the abstract nouns 'romance' and 'drama' cleverly remind readers of the Bard's (Shakespeare) genre of plays
- "loved" being in teh past tense may be indicating regret of his death with the bed being the only indication of her love
- The "spinning world" may be something which is in her own imagination or that their love made her disorientating which could have been both overwhelming and controlling
- In the first sentence there is significant amounts of imagery which shows how their love may have developed. It is also almose paying homage to some of Shakespeare's works
  + Forests could be a referene to to A Midsummer Night's Dream
  + Castles & torchlit = McBeth
  + This produces a semantic field of fantasy
  + This might reflect that their love was almost poetic and dreamy
- "he would dive for pearls" pearls beign precious & hard to find possibly being a metaphor for their love
- "a verb dancing in the centre of a noun" personifies the noun which
*** Structure
- The enjambment could indicate the almost incessant flowing rhythm of the speaker's desires
* The Great Gatsby
* Articles
* Adverts
* Speeches
* Propaganda Posters
* Course Structure
** General
- The course has a three part structure according to the three areas of exploration.
- No Assessment is tied to a particular part of the course so you can use any of the texts studied for any assessment (you cannot use the same work twice).
- The questions are very general which enables you to talk about whatever you want (relating to the question)
- Example questions from paper 2:
  + Referring to two of the works you have studied, discuss both how and why the text invites the reader to identify with situations, characters and/or ideas.
** Areas of Exploration
*** Readers, Writers and Texts
*** Time and Space
*** Intertextuality and connecting texts
** Fields of Inquiry
*** Culture, identity and community
*** Beliefs, power and justice
*** Art, creativity and the imagination
*** Science, technology and the environment
** Central Concepts
*** Identity
*** Culture
*** Creativity
*** Communication
*** Transformation
*** Perspective
*** Representation
** LangLit (SL)
Study of 4 literary works and at least 4 non-literary texts, covering:
 - 2 literary forms
 - 2 periods
 - 2 Places
 - 1 English work
 - 1 work in translation
 - 2 "Free choices"
** Works vs Texts
*** Literary Works
- Drama
- Poetry
- Prose: Fiction
- Prose Non-Fiction
*** Literary Texts
- Essays
- Biographies
- Letters
- etc.
** Breakdown of final Grade
| Exam            |   % |
|-----------------+-----|
| Exam Paper 1    | 35% |
| Exam Paper 2    | 35% |
| Oral Assessment | 30% |

*** Exam Paper 1
Unseen Guided Textual Analysis

The paper consists of two passages from two different non-literary text types, each accompanied by a question. Students choose one passage and write an analysis of it (20 marks)
*** Exam Paper 2
The paper consists od four general questions. In response to one question, students will
*** Oral Assessment (15 mins)
Supported by an extract from one literary work and one non-literary text, students will offer a prepared response of 15 minutes to the following prompt:
Examine the ways in thich the global issue of your choice
* Prep
** AUG
**** TODO Research into the background of Duffy
DEADLINE: <2020-08-31 Mon>
Focus on:
- her gender
- Find out about the other poems from her anthology (The world's wife)
- Feminism
- Use of Dramatic Monologue
