#+TITLE: English Language & Literature
#+NAME: Oscar Morris
#+TEACHER: Mr Proudfoot
#+ROOM: E4
#+STARTUP: fold

* Definitions
** Dramatic monologue
Poems inwhich one central narrator/speaker is presented usually in first person
* Ghosts
* The Crucible
* Poetry (Carol Ann Duffy)
** The World's Wife :anthology:
*** Themes
- Duffy's collection mostly focuses on the unheard perspectives of female counterparts of famous male figures
  + It is "giving a voice to the wives of famous and infamous 'great men' of world literature and civilisation" who often weren't heard nearly as much as the male writers
  + Even the titles give the females an identity
- It covers the issues surrounding marriage, sex, love, motherhood etc. being the "typical" roles of women
  + She tells of the cliche roles of woman and makes as if they are forced to live their lives as a steryotype
- She seems to be attempting to subvert the classical traditions of male poets and a female muse
- She often seems to mirror the literature of the husbands of those she is trying to portray for example "Anne Hathaway" is written as a sonnet mirroroing Shakespears's countless sonnets and "Mrs Darwin" is written almost as a diary entry mirroring Darwin's originals
*** Duffy as Poet Laureate
**** The position of Poet Laureate
- The origins of the Poet Laureateship date back to the 17th century (1616) when James I of England granted a pension to the writer Ben Jonson.
- Although there were subsequent court poets it was not until 1668 and the appointment of John Dryden by Charles II that the post was made an established royal office within the royal household.
- John Dryden was the only poet to have been removed from office due to him being a catholic convert he refused to take the oath of alliegance to the new protestant monarchs William III and Mary II.
- Druden's successor, Thomas Shadwell, introduced the custom of producing poems for the new year and for the monarchs birthday which became one of the key duties of the position.
- These duties later became an expectation rather than a requirement after the appointment of William Wordsworth
**** Duffy
- She became Poet Laureate in May 2009 following Andrew Motion and stood down in May of 2019 and was succeded by Simon Armitage
- She was considered for the position in 1999 however the PM at the time (Tony Blair) thought that she wouldn't be accepted due to her sexuality
  + The first female PM, Thatcher, was leader for 11 years so it might be considered contentious that Blair decided against Duffy in this prestigious role considering the fact that his infamous predecessor often celebrated her gender as being a means for differentiating herself as a polician
    - The former USSR media gave Thetcher the nickname 'The Iron Lady' due to her forceful personality and unwillingness to submit to other potentially aggressive leaders
    - In a famous speech she coined teh phrase 'the lady is not for turning' (meaning that as the PM she would not change her mind on government policy despite pressure from other parties)
- She was the first woman, first Scottish-born poet and the first known LGBT poet to hold the position
- As Poet Laureate Duffy wrote about current affairs auch as the war in Afghanistan, the deaths of the last two surviving British soldiers to have fought in WWI and the eruption of Eyjafjallajökull in April of 2010.
- She also wrote poems for the LGBT community which she was a part of
** Anne Hathaway :poem:
*** Context
**** Anne Hathaway herself
- She was Shakespeare's wife
- She was seven years older than Shakespeare when they married and Anne was already pregnant
- She was widowed before marrying Shakespeare
**** The Poem
- written in a sonnet form
  + 14 lines
  + usually ends in a rhyming couplet
  + usually 3 quartets
- comes from Her first themed collection of poems (The World's Wife)
- begins with an epigraph taken from Shakespeare's will leaving Anne his "second best bed" which was in fact the couple's maritial bed as the best was reserved for guests. Some critics have said that this was an insult however Duffy portrays this as Shakespeare's last romantic guesture to his wife. The beds of prosperous citizens were expensive often reaching prices equivalent to a small house. And it was customary for the wife to recieve the second best furniture and for the children to recieve the best. It was also customary for the best bed to be used for guests and the second best for the couple themselves.
- She is giving a voice to someone that may not have had a voice
*** The Bed
- can be seen as a aymbol for their everlasting love. She is able to look after the bed after her spouse has died.
- It has this symbolic value due to the context of the times
- It is used as a metaphor for their love
*** Their Love
- The line "Romance and drama played by touch, by scent, by taste." uses all of the senses gives us a sensory description which could reflect the physicality of their love furthermore Duffy's use of the abstract nouns 'romance' and 'drama' cleverly remind readers of the Bard's (Shakespeare) genre of plays
- "loved" being in teh past tense may be indicating regret of his death with the bed being the only indication of her love
- The "spinning world" may be something which is in her own imagination or that their love made her disorientating which could have been both overwhelming and controlling
- In the first sentence there is significant amounts of imagery which shows how their love may have developed. It is also almose paying homage to some of Shakespeare's works
  + Forests could be a referene to to A Midsummer Night's Dream
  + Castles & torchlit = McBeth
  + This produces a semantic field of fantasy
  + This might reflect that their love was almost poetic and dreamy
- "he would dive for pearls" pearls beign precious & hard to find possibly being a metaphor for their love
- "a verb dancing in the centre of a noun" personifies the noun which
*** Structure
- The enjambment could indicate the almost incessant flowing rhythm of the speaker's desires
** Mrs Darwin :poem:
*** The poem itself
Went to the Zoo
I said to him-
Somehting about that Chimpanzee reminds me of you.
*** Notes
- The hyphen in the second line could indicate her being cut off when speaking as many women would have been in those times
- "Went" could imply that she is being forced
- The consice length could imply that the wasn't allowed to speak/wasn't given a voice subtext perhaps???
- "Him" doesn't address him by name & the capital 'H' could indicate that he was superior to him as he was male due to:
  + his status
  + "Him" ('h' captialised) is usually used for God therefore inferring a Godlike power
    - Since the theory of the time was creationism by a cristian God and Darwin was disproving that therefore he could be compared to God
- "I" and "Him" being physically very close may indicate that they were actually equal
- "Cimpanzee" is somewhat instulting critizism reflecting an instulting tone, possibly because she is feeling neglected due to Darwin's obsesstion with his work. Duffy cleverly empowers the speaker by giving her language that her husband would understand
- She may have been the inspiration foe the theory of Evolution and maybe that the wives of famous males may have had some input into their husband's work
** Salome :poem:
*** IB Areas of Exploration
**** Identity
How does the theme of Identity come across in this poem?
- Towards the end of the poem she seems somewhat powerful - plosive alliteration in stanza 3 'the blighter, the beater or biter' somewhat of an Aggressive or volatile undertone as she is clearly capable of murder
- 'Never again' like a volta (turning point in a sonnet). Moves from the past to futurewith stronger feeling '!'
- a semantic field of violence "slaughter", "turf out" (phrasal verb), the plosives
- Doesn't know herself, lost/confused. mood - interrogative (questioning)
- psychopathic tendencies - not even aware of the identity of the man
  + repetitive nature of her killing could suggest that she has been numbed of any emotion
  + Duffy's use of parentheses (used to give extra information) could suggest that it isn't important
  + Could the poet be expressing the idea that females couldn't fully express themselves
  + "What did it matter?" as in that the identity of the man doesn't really matter
- Duffy defends and creates empathy for forgotten females
**** Representation
How are women represented in Duffy's *dramatic monologue* (one central character who is narating)
*** Context
- In the biblical story Herodias incites her daughter Salome to request the head of John the Baptist When offered a choice of reward for her dancing
- she was a real figure and the granddaughter of Herod the Great who killed lots of innocents
- She lived in a Patriarchy (male dominated society)
*** Language
- Patter - accent/dialect
- On the batter - drinking a lot socially probably intoxicated
- a generally informal register perhaps establishing her as of lower status & that her life may be disorganised
  + laid back
  + care free
    - "I knew I'd feel better" i.e. moves on quickly & doesn't really care
  + Informal Lexis (not worried about reputation)
    - "hungover"
    - "on the batter"
    - "fags"
- The poem generally goes against the idea of Patriarchy as Salome is generally aggressive/violent
- She is portrayed as a contemporary woman
- the bit in prns is more like a difinitive subtext as in Salome's thoughts are mirrored in the poem
- "- whose? -" The tone here is generally cynnical and devoid of emotion. She is clearly promiscuous, The reference to head in the line before could foreshadow John the Baptist's beheading. This idea  of the head representing the whole man is called synecdoche. "whose" is rethorical and Salome isn't expecting or really want an answer she just follows it with another question. There is rhyme in the first lines -- 'later' & 'matter' which she will continue throughout the poem
- "Good-looking, of course, dark hair, rather matted; the reddish beard several shades lighter" This is a description of how John the Baptist is usually depicted. His depiction is generally factual and almost cold-blooded who she seems to believe is only someone she has used for sex
- "very deep lines around the eyes, from pain I'd guess" She states that his lined face denotes pain which almost states that she has seen a lot of pain before, especially her casual tone
- "Peter? Simon? Andrew? John?" -- frequent interrogative mood, she isn't sure and could be confused/drunk/hungover, the names are all deciples, the reference to John is allusion (a reference to another story)
- The frequent ellipses may indicate that she is unsteady/intoxicated
- "Woke up with a head on the pillow beside me" possibly foreshadowing he sinister end to the poem
- There is ambiguity as "red beard" or "crimson mouth"
- "colder than pewter", "pain", "reddish beard" showing that there is a semantic field of deathly things
- The maid's innocence directly contrasts with Salome's premeditated evil
- There modern/informal imagery in her description of Salome's hangover cure
- the long list of names indicates that it almost doesn't matter who she slept with/killed
- There is maybe some solidarity in that both the maid and Salome are female
- She never confesses to killings when talking about cleaning up her act
- "cut out the booze and the fags and the sex" is a syndetic list (a list connected by conjunctions, in this case 'and'). This can emphasise the concept that these acts were generally frowned upon
- The similie "Like a lamb to the slaughter" ie that the men keep coming. The lamb is also a symbol of innocence also being a biblical image as lamb's were sacrifices
*** Structure
- Free verse however with some rhyme. it is a loose form of meter which could reflect teh irrational behavior of the speaker
- The half rhyme could reflect the speaker breaking the rules
- There is a somewhat loose rhythm to the poem reflecting her loose morals
** Today I am going to kill something. Anything.
*** Title
- phychopathic
- they are killing something and not someone
  + i.e. an indefinite pronoun
  + lack fo empathy
  + infers object
- fairly simple mono/duosyllabic language
  + i.e. a childish response
- a dark tone. i.e. sinister
- short sentence at the end for effect
* The Great Gatsby
* Articles
* Adverts
* Speeches
* Propaganda Posters
* Course Structure
** General
- The course has a three part structure according to the three areas of exploration.
- No Assessment is tied to a particular part of the course so you can use any of the texts studied for any assessment (you cannot use the same work twice).
- The questions are very general which enables you to talk about whatever you want (relating to the question)
- Example questions from paper 2:
  + Referring to two of the works you have studied, discuss both how and why the text invites the reader to identify with situations, characters and/or ideas.
** Areas of Exploration
*** Readers, Writers and Texts
*** Time and Space
*** Intertextuality and connecting texts
** Fields of Inquiry
*** Culture, identity and community
*** Beliefs, power and justice
*** Art, creativity and the imagination
*** Science, technology and the environment
** Central Concepts
*** Identity
*** Culture
*** Creativity
*** Communication
*** Transformation
*** Perspective
*** Representation
** LangLit (SL)
Study of 4 literary works and at least 4 non-literary texts, covering:
 - 2 literary forms
 - 2 periods
 - 2 Places
 - 1 English work
 - 1 work in translation
 - 2 "Free choices"
** Works vs Texts
*** Literary Works
- Drama
- Poetry
- Prose: Fiction
- Prose Non-Fiction
*** Literary Texts
- Essays
- Biographies
- Letters
- etc.
** Breakdown of final Grade
| Exam            |   % |
|-----------------+-----|
| Exam Paper 1    | 35% |
| Exam Paper 2    | 35% |
| Oral Assessment | 30% |

*** Exam Paper 1
Unseen Guided Textual Analysis

The paper consists of two passages from two different non-literary text types, each accompanied by a question. Students choose one passage and write an analysis of it (20 marks)
*** Exam Paper 2
The paper consists od four general questions. In response to one question, students will
*** Oral Assessment (15 mins)
Supported by an extract from one literary work and one non-literary text, students will offer a prepared response of 15 minutes to the following prompt:
Examine the ways in thich the global issue of your choice
* Prep
** AUG
**** DONE Research into the background of Duffy
DEADLINE: <2020-08-31 Mon>
Focus on:
- her gender
- Find out about the other poems from her anthology (The world's wife)
- Feminism
- Use of Dramatic Monologue
**** DONE answer the questions with 200 words each more info on google classroom

***** Q1
The poem "Salome" by Carol Ann Duffy is generally quite cynnical which is similar to how she likely was in real life. The form of the poem also supports this hypothesis as the poem is written in free verse without a regular rhyme which could reflect the abnormality of her life however Duffy ends 16 lines with consonantly rhymed words such as 'glitter' or 'slaughter' which could reflect that she often seems to repeat actions, these also give the poem cohesion and a sense of humour. Duffy has written the poem using the casual register (as defined by Martin Joos (1961)) or in-house/slang register (as defined by ISO 12620). Register is a way for sociolinguists to easily describe formality although being an aging term (with 'style' now being preferred), which in this case makes Salome seem less sophisticated than she probably was (being the daughter of a king) and also makes her seem more like a modern woman rather than living when she did. The poet chooses somewhat of a spoken diatype which is somewhat unusual for a written work however the poem almost seems to have been intended to be a thought rather than a formal piece of writing which also justifies the use of the casual register as desibed above.
***** Q2
The line "I knew I'd feel better for tea, dry toast, no butter" which is not the most appetising image for a lot of people seems somewhat strange (almost mirroring Salome's personality) however she must be able to recover from what seemed to be a somewhat alcohol filled night the day before which likely indicates her ability to recover from such a night with almost practised ease. The word 'pewter' contrasts with the language of the rest of the poem due to pewter's historical use and no longer being popular is the only real indication that the speaker is not a modern woman however without context this still could mean that she might have lived until the 18th century. In the line "her innocent clatter of cups and plates, her clearing of clutter, her regional patter" Duffy uses the plosive alliteration of both 'c' and 'p' sounds which are somewhat onomatopoeic to the sound she is trying to portray. The line "In the mirror, I saw my eyes glitter" which with what she discovers merely lines later indicates a fairly unusual amount of happiness at having somesone who she knows is dead sharing a bed with her.
