#+TITLE: Geography

* TODO download guide off of managebac
DEADLINE: <2020-08-26 Wed 19:00>

* Unit 1: Changing Population PG 388- :Paper 2:
** Key Terms
*** North-South divide
The increasing inequality in levels of development between the North and the South or between HICs and LICs.
*** Development gap
The difference in wealth between the developed world (North) and the devloping world (south).
*** OPEC
The organisation of Petroleum Exporting Countries, representing the interests of oil exporters. Its position is undermined by some oil producing countries such as the UK, which does not agree with OPEC-controlled oil prices.
*** The G7/G8
A group of the world's wealthiest and most powerful countries.
*** The G10 or Paris Club
A group representing the wealthiest members of teh International Monetary Fund.
** 1.1 Population and Economic development patterns
** 1.2
** 1.3
* Unit 2: Core: Global climate - vulnerability & resilience
* Option D: Geophysical Hazards
* Option E: Liesure, Tourism & Sport
* Internal Assessment
