#+TITLE: German

* Some writing
** 1.
In den Sommerferien war ich eine ganze maenge zu hause wie alle anderen aber ungefaehr in der mitte von den Ferien haben meine zwei Sportarten angefangen, also Segeln und Tennis spielen, die beide sehr viel Spass machen. Nach ein paar wochen gab es in eins von meiner Segelclubs eine Traeningswoche fur die Jugendlichen wo ich dabei geholfen habe. Da habe ich auch die erste ausbildung um Segellehrer zu verden. In der Woche war das wetter eigentlich ganz gut fuer die angfaenger zu lernen aber auch gut fuer mich aleine zu segeln. Ich habe seit ungefaehr fuenf jahre gesegelt und ich habe in ein kleinen Dorf im Norden von Deutschland (eine halbe Stunde Suedlich von Flensburg). Ich habe auch in einer Tennis Traeningswoche mit gemacht, dies mal als schueler und es hatt auch viel Spass gemacht mitt anderen zu sein. Ich war eigentlich ganz gemuetlich zu hause weil ich eine ganze maenge programmiere und damit habe ich auch eine ganze maenge gelernt also war das ganze zu hause bleiben nicht so schlimm aber ich habe raus gekrigt dass es auch fuer mir nett ist andere leute zu sehen. Zum ende den Sommerferien hatte ich auch waenigere projekte zu machen also damit bin ich zufrieden wieder in die schule zu gehen, ich hatte ein bisschen lange weile. Leider denke ich nicht dass die segel Regattaseson noch passieren wirt aber waenigstens macht die RYAS ueber den Winter Traening also ist es eigentlich nicht so schlimm (auch wenn es im Winter ganz schoen kalt ist, auch mitt dickem Neopraenanzug). Mitt dem Tennis mache ich jeden Mitwoch Abend gruppen Unterricht und jeden Montag Abend mache ich einsel Unterricht. In meinem Tennisclub wolten die meisten anderen das ich mit ihnen in die Clubmanschaft komme aber wolte ich eigentlich noch nicht aber wir werden sehen ob ich jetzt mehr in der manchaft mache.
** 2.
Wegend die ganze Coronageschichte dachte ich dass das meiste gut gelaufen ist also weil ich eigentlich nicht ein sozialer mensch bin
* Erfarungen: Deutsche Geschichte - getrenntes Deutchland
* Erfarungen 2:2 eine kulinarische Reise
* Erfarungen 2:3 Feste und Traditionen
* Kommunikation und Medien - Fernsehen, Kino, Werbung
* Soziale Beziehungen - Jugend und Internet : Internet Schule
* Identitaet 1:3 Werte und Glauben
* Soziale Organisation
* Wissenschaft und Technik - Generation Internet und Cybermobbing
* Freizeit: Fussball - eine Maenner domaene?
* Identitaet 1:4 Wir und die Anderen
* Erfahrungen 2:1 Praegende Einfluesse
