#+TITLE: German

* Some writing
** 1.
In den Sommerferien war ich eine ganze maenge zu hause wie alle anderen aber ungefaehr in der mitte von den Ferien haben meine zwei Sportarten angefangen, also Segeln und Tennis spielen, die beide sehr viel Spass machen. Nach ein paar wochen gab es in eins von meiner Segelclubs eine Traeningswoche fur die Jugendlichen wo ich dabei geholfen habe. Da habe ich auch die erste ausbildung um Segellehrer zu verden. In der Woche war das wetter eigentlich ganz gut fuer die angfaenger zu lernen aber auch gut fuer mich aleine zu segeln. Ich habe seit ungefaehr fuenf jahre gesegelt und ich habe in ein kleinen Dorf im Norden von Deutschland (eine halbe Stunde Suedlich von Flensburg)
* Erfarungen: Deutsche Geschichte - getrenntes Deutchland
* Erfarungen 2:2 eine kulinarische Reise
* Erfarungen 2:3 Feste und Traditionen
* Kommunikation und Medien - Fernsehen, Kino, Werbung
* Soziale Beziehungen - Jugend und Internet : Internet Schule
* Identitaet 1:3 Werte und Glauben
* Soziale Organisation
* Wissenschaft und Technik - Generation Internet und Cybermobbing
* Freizeit: Fussball - eine Maenner domaene?
* Identitaet 1:4 Wir und die Anderen
* Erfahrungen 2:1 Praegende Einfluesse
