#+TITLE: German
#+STARTUP: fold

* Some writing
** 1.
In den Sommerferien war ich eine ganze maenge zu hause wie alle anderen aber ungefaehr in der mitte von den Ferien haben meine zwei Sportarten angefangen, also Segeln und Tennis spielen, die beide sehr viel Spass machen. Nach ein paar wochen gab es in eins von meiner Segelclubs eine Traeningswoche fur die Jugendlichen wo ich dabei geholfen habe. Da habe ich auch die erste ausbildung um Segellehrer zu verden. In der Woche war das wetter eigentlich ganz gut fuer die angfaenger zu lernen aber auch gut fuer mich aleine zu segeln. Ich habe seit ungefaehr fuenf jahre gesegelt und ich habe in ein kleinen Dorf im Norden von Deutschland (eine halbe Stunde Suedlich von Flensburg). Ich habe auch in einer Tennis Traeningswoche mit gemacht, dies mal als schueler und es hatt auch viel Spass gemacht mitt anderen zu sein. Ich war eigentlich ganz gemuetlich zu hause weil ich eine ganze maenge programmiere und damit habe ich auch eine ganze maenge gelernt also war das ganze zu hause bleiben nicht so schlimm aber ich habe raus gekrigt dass es auch fuer mir nett ist andere leute zu sehen. Zum ende den Sommerferien hatte ich auch waenigere projekte zu machen also damit bin ich zufrieden wieder in die schule zu gehen, ich hatte ein bisschen lange weile. Leider denke ich nicht dass die segel Regattaseson noch passieren wirt aber waenigstens macht die RYAS ueber den Winter Traening also ist es eigentlich nicht so schlimm (auch wenn es im Winter ganz schoen kalt ist, auch mitt dickem Neopraenanzug). Mitt dem Tennis mache ich jeden Mitwoch Abend gruppen Unterricht und jeden Montag Abend mache ich einsel Unterricht. In meinem Tennisclub wolten die meisten anderen das ich mit ihnen in die Clubmanschaft komme aber wolte ich eigentlich noch nicht aber wir werden sehen ob ich jetzt mehr in der manchaft mache.
** 2.
Wegend der ganze Coronageschichte dachte ich dass das meiste gut gelaufen ist also weil ich eigentlich nicht ein sozialer mensch bin und mein meistes Leben digital ist war das nicht so schwerich zu das ganze online Schule zu adaptieren. Weil ich auch viel programmiere habe ich eine ganze menge gelernt und ich habe mir mit Linux und so weiter vorberitet also kann ich jetzt viel schneller was schreiben und bin viel flexiebler mitt wass ich programmieren kann. Eigentlich wollte meine familie diesen Sommer nach Greichenland um eine Woche auf einer yacht zu segeln da um die Inseln aber leider hat das auch ausgefallen. Ich segel auch ganz gerne und segel auch Regatta und viel segeln gab es nicht un dann war das wetter die letzten paar wochen (fuer das segeln) nicht so gut also habe ich dann ein bisschen arbeit an meinem Boot gemacht. Meine Sportarten waren mit den ersten die mann in Schottland wieder machen konnte naemlich Segeln und Tennis spielen. Leider darf mann immernoch nicht zu Regatten hin fahren aber wenichtens gibt es die Clubregatten wo ich mitt mache. Diesen Sommer wollte ich auch zu der Nationalregatta in Cornwall fahren aber naturlich hatt das nicht geklappt wegen Corona. Es gibt auch eine Regatteserie wo jede paar wochen gibt es eine Regatte um Schottland verteilt und da wollte ich die meisten von mitt machen wo auch die Schottische Meisterschaften (fuer meiner Bootsklasse) mit drinnen sind. Den Winter ueber gibt es auch Regattatraining wo ich mit machen wird.
* Erfarungen: Deutsche Geschichte - getrenntes Deutchland
** Goodbye Lenin
*** 1a
**** Uber die Mutter
- Sie ist Sozialisten
- Ihr Mann ist im westen geblieben
- Sie liegt im koma fuer 8 monaten
**** Uber Alex
- er liebt seine Mutter
- weil sie Sozialisten war glaubt er das wenn sie heraus finded das Deutschland sich wieder vereinigt hatt das sie von noch ein Hertz Infakt erleidigt wird.
- Dass wegen produziert er mitt Denis die Aktuellen Kamera, eine Narchichten Ferhnsehsendung so dass seine Mutter das nicht heraus finded dass Deutschland eines land ist.
**** Uber den Vater
- er ist bei einer Dienstreise in den Westen geblieben und seine Frau sollte mit den kindern mit ziehen.
- er hatt jeden Tag an seine Kinder gedacht
- er besucht sine ehrmalige Frau im krankenhaus als sie im Sterben liegt
**** Uber die DDR
- das leben var schlechter als im westen weil Roberts haus so viel groesser war
- Es gab weniger freiheit als im Westen also man konnte nur fuer eine Partei vehlen
*** 1b
| Die Mutter  | Alex      |
|-------------+-----------|
| sympathisch | energisch |
| lieb        | fanatisch |
| sorglos     | activ     |
| passiv      | depressiv |
| engagiert   | komisch   |
| lustig      | naiv      |
| glucklich   |           |
*** 2
In der DDR lebten die meisten ziemlich gleich also sie wohnten in einer wohnung die ziemlich grau war sie hatten damals schon altmodiche kleidung und moebeln. Alexs Mutter war ziemlich hoch in der SED also hat sie sich eigentlich gut verhalten aber die meisten anderen konnten das in der DDR nicht. Fuer die Mutter von Alex war es wichtig ist ihr beliebtes Sozialismus.
* Erfarungen 2:2 eine kulinarische Reise
* Erfarungen 2:3 Feste und Traditionen
* Kommunikation und Medien - Fernsehen, Kino, Werbung
* Soziale Beziehungen - Jugend und Internet : Internet Schule
* Identitaet 1:3 Werte und Glauben
* Soziale Organisation
* Wissenschaft und Technik - Generation Internet und Cybermobbing
* Freizeit: Fussball - eine Maenner domaene?
* Identitaet 1:4 Wir und die Anderen
* Erfahrungen 2:1 Praegende Einfluesse
* Hausaufgaben
** Aug
*** DONE Das Ding wass per email geschiged worde lesen
DEADLINE: <2020-09-08 Tue 10:20>
*** DONE Do questions 1-4 & read thingy on PG 75-77
DEADLINE: <2020-09-07 Mon 09:00>

1. Q1
   a) 6
   b) 5
   c) 1
   d) 8
   e) 3
   f) 4
   g) 7
   h) 2
2. Q2
   a) "Die meisten haben eine andere Religion als wir Europaeer" ist ziemlich richtig und die Schueler gehen in einer Moschee wo die meisten Tuerken beten, aber "Die leben doch so wie wir"
   b) "Ueberall gibt es Gekritzel an den Waenden" davon wird nicht gesprochen aber Sie dachte das "In Kreutzbetg laufen ganz viele Punks herum" was nicht ganz richtig war
   c) "Michael hat von Strassengangs gehoert ... aber das war gar nicht so"
3. Diese Rundgaege haben offentsichlicht ein Effect weil die meisten kinder schlechte Vorurteile hatten und es ihnen gezeigt wurde das es nicht so wirklich ist.
4. Q4
   a) Migranten
   b) Juden
   c) Bekannten
   d) Park
   e) Kinderbauernhof
   f) Innen
*** DONE Read the rest of the pdf after the questions done in class except Pg 24 until Pg 26
DEADLINE: <2020-09-15 Tue>

**** Pg 17
1) b
2) c
**** Pg 18
1) c
2) b
**** Pg 19
oft falsch gelaufen
**** Pg 20
Die Wachposten mussten ueber die mauer gucken und sie hatten den bewies to schiessen fals irgendjemand ueber die mauer wollte.
**** Pg 26
Liebe Tante,
Du hast sicher gehoert dass vor ein paar tagen die Mauer in Berlin gefallen ist und die Grenzen wieder geoeffnet sind. Persoenlich finde ich das sehr beruhigend das wir jetzt ueber ganz deutschland leicht reisen koennen und entlich euch wieder sehen zu koennen.
Liebe Gruesse Oscar
*** DONE Do the questions 1a & 1b on the AQA gb lenin sheet thingy
DEADLINE: <2020-09-14 Mon>

**** 1 a
1) R
2) R
3) F
4) F
5) NA
6) F
7) R
8) NA
**** 1 b
***** Hallo Papa
Christiane admits that their father (Robert) didn't leave because of another woman, but because his life was made too difficult because he didn't want to join the party. Shortly afterwards, their mother has another heart attack, so Alex visits his father, so that Robert can see Christiane for a last time.
***** Gschichte un Geschichten
Alex and Denis (a collegue) become directors of an invented truth: Erich Honecker resigns and Sigmund Jaehn (first german astronaut) will become general secretary of the SED. He decides to open the borders to better share socialism with the world. Christiane pretends to believe it even though Lara already told her the truth. Christiane dies three days later.
*** DONE Prepare a short presentation of ostalgie and ost produkte
- nicht viel von der Ost-Detuschen kultur gibt es noch auser ungefaehr zwei sachen naehmlich das Sandmaennchen und die Ampelmaenner in Berlin
- Diese sachen sind jetzt fast fuer die touristen das wichtige
- Auch jetzt kann mann in Berlin eine sogenannte 'Trabbi Tour' machen.
  + Als die Grenzen wieder offen wahren und die Ostdeutschen im westen gegangen sind gab es viele unfalle weil in Ostdeutschland als mann auf die autobahn fuhre ist mann angehalten und fuer eine luecke gewartet und dann wieder loss gefahren. und dann such konneten die Trabbis nicht so gut beschloinigen als die westlichen autos.
- Das Sandmaennchen kann man immernoch auf den kinder fehrnsehkanalen sehen
- Die Ostdeutschen Ampelmaenner gibt es auch immernoch in ost und west Berlin
*** TODO Read Pg 18-30 in the play thingy
