#+TITLE: Theory of knowledge
#+STARTUP: fold

* Knowledge & the Knower
- underpinned by the question how do we know stuff
** What criteria can we use to distinguish between knowledge, belief & opinion?
3 things that we feel we know
1. I know this room has at least one radiator 2
2. I know that I cannot know that anything is true 1
** Video things
- terms about knowledge are really well defined
- there is a difference between an assertion and a proposition
  + Assertion - linguistic act either spoken or written that has a truth value
  + Proposition - the content of your assertion i.e. th eunderlying meaning of what your saying
  + Truth value - the state of being true or false or indeterninate
  + Assertion changea with language however proposition doesn't
- Belief is when you take a propositional attitude is truth (i.e. you think it is true)
- the traditional def. of knowledge is justified belief
- Justification - evidence or other support of belief
- testimony - taking someone's word for it
  + i.e. books or new reports
- First person experience is somewhat self explanatory
- Gettier cases - situations in which you can have justified true beliefs but accidentally and therefore is not knowledge
* Cultural Community
** Membership
- St Leonards
- UK i.e. the laws can change what you think is correct which comes from your upbringing
- Western Europe
- Western powers
- Religion (I don't follow any religion)
- family/friend group
** Knowledge from without communities
- surroundings
- personal experiences
* Maps
- flat maps cannot be objective
* something
Writing assignment

1) I would make sure to teach them on grass to prevent nervousness. I would start by telling them the basic idea behind pedaling. I would then show them how to get onto the bike. After they know how to mount the bike I would help them push off by holding them and running along with them to make sure they don’t fall. If they are nervous I would tell them that I’ll support them from behind.
2) No, not helpful. A child wouldn’t understand the meaning of that phrase and even after explaining it to them, they wouldn’t know how to utilise this knowledge.
3) A male obstetrician would know more about the theory of childbirth however would not understand the emotions and feelings of the experience. A male obstetrician has more knowledge of childbirth in the sense that knowledge is a justified true belief.
* Quote
- it may be saying thet we are completely influenced by those around us and our non-living environment
- co-authors are the people around us
- if it is saying what is stated above then yes
- depends how you define knowing yourself
